"""add confirmed_column_to user

Revision ID: f787d46cbfd1
Revises: 7180e9015ea7
Create Date: 2024-02-23 18:52:51.486387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f787d46cbfd1'
down_revision: Union[str, None] = '7180e9015ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
