version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: my_redis_cache
    ports:
      - "6379:6379"
